import type { Addon, BoatListing } from './types';

export const demoBoats: BoatListing[] = [
  {
    id: 'demo-sundancer',
    marinaId: 'demo-table-rock',
    name: 'Sundancer 230',
    type: 'Pontoon',
    capacity: 10,
    dailyRate: 425,
    hourlyRate: 85,
    status: 'available',
    rating: 4.9,
    reviewCount: 42,
    marina: { id: 'demo-table-rock', name: 'Indian Point Marina', lake: 'Table Rock Lake', city: 'Branson', state: 'MO' },
    description: 'A spacious, easygoing pontoon made for long lunches, hidden coves, and a full day with your favorite people.',
    amenities: ['Bluetooth audio', 'Bimini top', 'Swim ladder', 'Cooler', 'Life jackets'],
    photoUrls: ['https://images.unsplash.com/photo-1566847438217-76e82d383f84?auto=format&fit=crop&w=1400&q=85'],
    reviews: [
      { id: 'r1', rating: 5, comment: 'Beautiful boat and a painless pickup. Our family had the best day.', createdAt: '2026-05-18', user: { name: 'Maya R.' } },
      { id: 'r2', rating: 5, comment: 'Clean, comfortable, and exactly as pictured.', createdAt: '2026-04-29', user: { name: 'Evan T.' } },
    ],
  },
  {
    id: 'demo-monterey',
    marinaId: 'demo-ozarks',
    name: 'Monterey M-22',
    type: 'Ski Boat',
    capacity: 8,
    dailyRate: 595,
    hourlyRate: 120,
    status: 'available',
    rating: 4.8,
    reviewCount: 31,
    marina: { id: 'demo-ozarks', name: 'Grand Glaize Marina', lake: 'Lake of the Ozarks', city: 'Osage Beach', state: 'MO' },
    description: 'A sporty bowrider with plenty of power for tubing, skiing, and exploring every corner of the lake.',
    amenities: ['Wake tower', 'Premium audio', 'GPS', 'Tube included', 'Captain available'],
    photoUrls: ['https://images.unsplash.com/photo-1540946485063-a40da27545f8?auto=format&fit=crop&w=1400&q=85'],
    reviews: [{ id: 'r3', rating: 5, comment: 'Fast, smooth, and an absolute blast.', createdAt: '2026-05-03', user: { name: 'Noah K.' } }],
  },
  {
    id: 'demo-bayliner',
    marinaId: 'demo-murray',
    name: 'Bayliner Element',
    type: 'Deck Boat',
    capacity: 9,
    dailyRate: 375,
    hourlyRate: 78,
    status: 'available',
    rating: 4.7,
    reviewCount: 19,
    marina: { id: 'demo-murray', name: 'Lighthouse Marina', lake: 'Lake Murray', city: 'Chapin', state: 'SC' },
    description: 'Stable, roomy, and simple to handle. A great choice for swimming, cruising, and first-time captains.',
    amenities: ['Depth finder', 'Shade canopy', 'Swim platform', 'Dry storage'],
    photoUrls: ['https://images.unsplash.com/photo-1562281302-809108fd533c?auto=format&fit=crop&w=1400&q=85'],
  },
  {
    id: 'demo-seadoo',
    marinaId: 'demo-table-rock',
    name: 'Sea-Doo GTX 170',
    type: 'Jet Ski',
    capacity: 3,
    dailyRate: 285,
    hourlyRate: 72,
    status: 'available',
    rating: 4.9,
    reviewCount: 27,
    marina: { id: 'demo-table-rock', name: 'Indian Point Marina', lake: 'Table Rock Lake', city: 'Branson', state: 'MO' },
    description: 'Responsive, comfortable, and ready for an energetic day on open water.',
    amenities: ['Watertight storage', 'Boarding ladder', 'Life jackets', 'Safety briefing'],
    photoUrls: ['https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=1400&q=85'],
  },
  {
    id: 'demo-bass',
    marinaId: 'demo-taneycomo',
    name: 'Ranger Z520R',
    type: 'Fishing',
    capacity: 4,
    dailyRate: 340,
    hourlyRate: 68,
    status: 'available',
    rating: 4.8,
    reviewCount: 16,
    marina: { id: 'demo-taneycomo', name: 'Lilleys Landing', lake: 'Lake Taneycomo', city: 'Branson', state: 'MO' },
    description: 'A tournament-ready fishing boat with the electronics and deck space serious anglers expect.',
    amenities: ['Trolling motor', 'Fish finder', 'Livewell', 'Rod storage'],
    photoUrls: ['https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1400&q=85'],
  },
  {
    id: 'demo-avalon',
    marinaId: 'demo-murray',
    name: 'Avalon Catalina',
    type: 'Pontoon',
    capacity: 12,
    dailyRate: 465,
    hourlyRate: 92,
    status: 'available',
    rating: 4.9,
    reviewCount: 38,
    marina: { id: 'demo-murray', name: 'Lighthouse Marina', lake: 'Lake Murray', city: 'Chapin', state: 'SC' },
    description: 'A polished tritoon with plush seating and room for the whole crew.',
    amenities: ['Premium sound', 'Double bimini', 'Table', 'Cooler', 'USB charging'],
    photoUrls: ['https://images.unsplash.com/photo-1530053969600-caed2596d242?auto=format&fit=crop&w=1400&q=85'],
  },
];

export const demoAddons: Addon[] = [
  { id: 'demo-tube', marinaId: 'demo', name: 'Towable tube', price: 45, description: 'Two-person tube, rope, and pump' },
  { id: 'demo-cooler', marinaId: 'demo', name: 'Stocked cooler', price: 35, description: 'Ice, water, and soft drinks' },
  { id: 'demo-captain', marinaId: 'demo', name: 'Local captain', price: 180, description: 'Four hours with a licensed captain' },
];
